### ISSUE TITLE
inv_to_df column names

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#142]
I noticed that the column names for the start and end times in the DataFrame that results from `inv_to_df` are `start_date` and `end_date`. Do we want to change these to be `starttime` and `endtime` to be consistent with everything else, or is there a reason for their naming?

Changing it is trivial, but it is probably going to break everything that uses it (fixing that is also trivial, but a PITA nonetheless).

**Comment by sboltz** [comment]
Yes,  this is due to `obspy.Channel` having a `start_date` and `end_date` attribute rather than `starttime` and `endtime` as is used in the `obspy.Catalog` tree. I suspect this discrepancy is due to is a difference in notation between stationXML and quakeML. I am not sure if, in this case, it would be better to stick as closely to obspy attribute names as possible or be as consistent as possible between dataframe columns extracted from different data types. I would be inclined to leave it as-is but I am certainly open to more discussion.

**Comment by d-chambers** [comment]
Yes, this is due to obspy.Channel having a start_date and end_date attribute rather than starttime and endtime as is used in the obspy.Catalog tree. I suspect this discrepancy is due to is a difference in notation between stationXML and quakeML. I am not sure if, in this case, it would be better to stick as closely to obspy attribute names as possible or be as consistent as possible between dataframe columns extracted from different data types. I would be inclined to leave it as-is but I am certainly open to more discussion.

**Comment by d-chambers** [comment]
Ok, leaving for now to maintain parity with ObsPy's data structures.
