### ISSUE TITLE
get_waveforms() method using starttime, endtime needs clarity (or possibly a fix) to ensure all waveforms span the window

### ISSUE THREAD

**Issue by El-minadero** [niosh-mining/obsplus#16]
* obsplus version: 0.0.0
* Python version: 3.6
* Operating System: macOS High Sierra 10.13.6

### Description
use of wavebank to get timeseries spanning from one time t1, to another t2 returns all waveforms which have some time in-between. There is thus some ambiguity in the documentation whether 'returns waveforms which match starttime, endtime..' means produce waves which span from time t1 - t2, or just returns some amount of data from this time. 

I personally think there is some utility in having a flag, option, or alternate method which requires waveforms to span the times between t1 and t2, especially for crosscorrelation purposes. However, I can also see current behavior being useful.

### What I Did

I discovered it with this:
```
 print(end-start)
        streams = wavebank.get_waveforms(starttime=start, endtime=end)
        for stream in streams:
            print(len(stream.data))
            print(stream.stats.starttime)
            print(stream.stats.endtime)
            print(stream.stats.sampling_rate)
        pass
```
Which gives the following output:
```
3600.0
900001
2017-09-24T15:29:52.180000Z
2017-09-24T16:29:52.180220Z
249.99998474121094
900001
2017-09-24T15:29:52.180000Z
2017-09-24T16:29:52.180220Z
249.99998474121094
900001
2017-09-24T15:29:52.180000Z
2017-09-24T16:29:52.180220Z
249.99998474121094
225353
2017-09-24T16:14:50.772000Z
2017-09-24T16:29:52.180055Z
249.99998474121094
225353
2017-09-24T16:14:50.772000Z
2017-09-24T16:29:52.180055Z
249.99998474121094
225353
2017-09-24T16:14:50.772000Z
2017-09-24T16:29:52.180055Z
249.99998474121094
```
you can see that wavebank returned two different sets of streams, one with ~900001 samples and one with ~225353.

**Comment by d-chambers** [comment]
hmmm... good point. The `WaveBank.get_waveforms` method should behave as similarly to the FDSN `Client`'s `get_waveforms` method as possible. I believe the FDSN `Client` will just return all available data regardless of gaps or data incompleteness, but I will double check (maybe @calum-chamberlain knows of the top of his head?). Either way, a clear description on how this is handled in the docs is a good idea.

After creating the stream it should be straight-forward to drop traces that don't meet some duration requirement:

```python
# assuming you have already defined t1, t2, and st
duration = t2 - t1
buffer = 1  # small buffer for duration to avoid rejecting traces off by one sample
st.traces = [x for x in st if (x.stats.endtime - x.stats.starttime) >= (duration - buffer)]


```

**Comment by calum-chamberlain** [comment]
From the [FDSN spec](http://www.fdsn.org/webservices/FDSN-WS-Specifications-1.1.pdf), page 6:

> The starttime parameter should be	interpreted	as	selecting	any	data	or	information	(time series samples, earthquake	origins,	metadata	epochs)	at	times	on	or	later	than	the	value	specified.		
Similarly,	the	endtime selects	any	data	or	information	at	times	on	or	prior	to	the	value	specified.		
The	selection	shall	include	any	metadata	epochs	intersecting	with	the	specified	time	range.

**Comment by calum-chamberlain** [comment]
I interpret that to mean that any data-sample that lies between the `starttime` and `endtime` should be returned, but yes, some doc-string to say that this is what is being done could be useful.
As an aside, different data centres interpret this in different ways, see [this issue](https://github.com/GeoNet/fdsn/issues/78) at GeoNet (New Zealand) for a little discussion, @nbalfour had useful comments and notes from the FDSN spec. GeoNet doesn't trim data to the exact length (IRIS does) because this is more efficient on their end.

**Comment by d-chambers** [comment]
Thanks @calum-chamberlain for the references. 

So @El-minadero, the current behavior for `get_waveforms` is correct. I don't want to add many (maybe any) extra parameters to the `get_waveforms` method that the obspy `Clients` don't support so that data sources can be switched out without changing application code. I normally wouldn't be opposed to adding  a separate method to do what you are asking but since there are many, many ways to deal with missing data/gaps it may be best to just let the user/end application deal with this for now. Added an item to clarify docs in #17. 

A configurable client wrapper for handling quality issues (like gaps/missing data) which could be applied to any datasource (like `WaveBank`) could be a worthwhile pursuit but I don't current have the time to work on it. Closing for now, re-open if there should be more discussion.

**Comment by El-minadero** [comment]
@d-chambers 
Fair enough. Luckily there are some easy ways to get around it for my purposes, but figured it was worth bringing up.
