### ISSUE TITLE
Release 0.2.2

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#254]
We haven't done a release in a while and there are a few bug fixes in master now. Anything else anyone wants to add (@sboltz) before a bug fix release?

**Comment by shawnboltz** [comment]
@d-chambers I'm not sure. There's some kind of issue with how paths are stored in the indices for the WaveBank (and probably the EventBank as well) that I'm still trying to pin down. I haven't opened an issue for it yet because I am not sure what the actual problem is other than it involves inconsistencies with relative and absolute paths and the presence of a leading backslash. I don't know if we want to try and address it now or in the next release.

I might pick your brain on it, though, to figure out what the correct behavior is supposed to be.

**Comment by d-chambers** [comment]
Where do you see the issue crop up? Only one windows? Can you give me a reproducible example?

**Comment by d-chambers** [comment]
We certainly don't want to do a release if there is a serious bug outstanding

**Comment by shawnboltz** [comment]
There have been two situations with the bug(s), one of which is a bit of an extreme case that I don't think will crop up often. The other might be more important to deal with and I have observed it in both Linux and Windows. I'll go ahead and make an issue for it and we can move over there.

**Comment by shawnboltz** [comment]
Okay @d-chambers, see #255

**Comment by d-chambers** [comment]
closed with release 0.2.4
