### ISSUE TITLE
Bank use in multiprocessing

### ISSUE THREAD

**Issue by El-minadero** [niosh-mining/obsplus#96]
### Description

for many seismology processing steps, parallel compute is a necessity. Wavebank, EventBank, and StationBank are excellent, fast, and clean interfaces for accessing  data on disk. However their internal implementations are not suited for distributed computing, (e.g. multiprocessing module)

One way of addressing this might be a lightweight, zero parent class equivalent that only implements accessor methods. Here's an example:

```python
# make wavebank
data_on_disk = '.....'
wavebank = WaveBank(data_on_disk)
wavebank.update_index()

# get lightweight version
read_only_wavebank = wavebank.get_readonly_version()

# create arguments for multiprocessing

jobs = [x for x in range(0,100)]
job_args = []
for job in jobs:
    a_copy = read_only_wavebank.copy()
    job_args.append( ( job, a_copy ) )

# pass on to multiprocessing module

```

There might be additional complications if dependencies are needed to replicate the behavior of get_waveforms() or yield_waveforms(), but this approach might be worth considering.

**Comment by d-chambers** [comment]
First off it should be made clear that the Banks of ObsPlus aren't trying to be a big-data distributed database in any sense. Rather, their philosophy is rather like SQLite; It should be very easy to get started with them, and relatively painless to switch to something more heavy duty if you outgrow them.   

Having stated that, can you be more specific about what requirements they do not meet? By "distributed" do you mean distributed across processes only or also across machines (without a common file system)? If you need to distributed across machines you have probably outgrown ObsPlus' banks. 

In the case of `WaveBank` an HDF5 index is used, which is safe for many concurrent reads. As long as you don't call the `update_index` method you can use as many as you like. Since `EventBank` uses SQLite you can have as many reading/writing processes as you like. The only catch is that each process must have access to the index file.  

> zero parent class

I am not sure what the object's method resolution order (MRO) would have to do with its suitability for these types of applications. Is enforcing *immutability* what you are concerned about? Like I said above, as long as you don't call the `update_x` methods the state of the indices will not change so you shouldn't have any issues.

**Comment by El-minadero** [comment]
Interesting. So if a routine uses the same 'bank' which is copied across processes, it should function fine? I see a ton of utility in say, distributed loading and processing of waveforms using dask or something similar, especially when paired with the to_xarray() functionality. 

let me experiment a bit and see if/where any improvement is needed.

**Comment by d-chambers** [comment]
Sure, sounds good.

**Comment by El-minadero** [comment]
So, I tested WaveBank under the hood in my ambient noise crosscorrelation project (on the UUSS git page) with dask, and it seems to not be giving any error messages, nor does it seem to slow down the parallel ops at all. I think it might be ok to close this issue till something else comes up.

**Comment by d-chambers** [comment]
Nice, can you share a link to your repo?

**Comment by El-minadero** [comment]
yeah. [anxcor](https://github.com/uofuseismo/anxcor). Still pretty rough at the moment but Its getting there!

**Comment by d-chambers** [comment]
Nice, I am glad to see it has tests. Closing for now, reopen if you run into issues.
